In [43]:
import pandas as pd

census = pd.read_csv("censusChicago.csv")

census

forecast = pd.read_csv("Socioeconomic_Forecast.csv")



population = pd.read_csv("population.csv")
forecast

,FID,OBJECTID_1,Shape_Leng,Shape_Area,COUNTY,GEO_ID,SUBZONE_09,LAZ,LAZ_GEO,HH_2015,...,PHH_2040,EMP_2040,HH_2045,PHH_2045,EMP_2045,HH_2050,PHH_2050,EMP_2050,Shape__Area,Shape__Length
0,1,801,10513.961078,6.909522e+06,111,00607,4558,111-u00607-04558,Unincorporated Alden Township,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.178611e+06,4342.391650
1,2,802,7107.455589,2.562580e+06,97,52753,7416,097-u52753-07416,Unincorporated Newport Township,7,...,51.662677,6.462701,23.994073,51.662677,6.462436,23.998634,51.662677,6.462218,4.370797e+05,2934.546022
2,3,803,10533.500461,6.934657e+06,111,00607,4559,111-u00607-04559,Unincorporated Alden Township,1,...,2.453019,0.000000,0.995548,2.453019,0.000000,0.996687,2.453019,0.000000,1.182899e+06,4350.444114
3,4,804,10513.235212,6.907583e+06,111,63654,5731,111-u63654-05731,Unincorporated Richmond Township,4,...,13.755885,0.000000,4.902956,14.413843,0.000000,5.714041,16.093231,0.000000,1.178294e+06,4342.149221
4,5,805,10533.284799,6.934356e+06,111,00607,4560,111-u00607-04560,Unincorporated Alden Township,10,...,36.016482,24.732784,15.641778,36.016482,24.732492,15.647362,36.016482,24.732252,1.182848e+06,4350.354966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21972,21973,21196,12781.172840,6.500097e+06,197,12476,12212,197-i12476-12212,Channahon,161,...,502.378136,83.817483,180.635264,502.378136,83.817228,180.449617,502.378136,83.817018,1.075711e+06,5200.488233
21973,21974,21197,13021.718624,5.117786e+06,197,12476,12211,197-i12476-12211,Channahon,130,...,497.059526,34.904338,143.307891,497.059526,35.173906,143.159539,497.059526,35.449124,8.469338e+05,5299.132600
21974,21975,21198,13808.081184,6.161278e+06,197,12476,12210,197-i12476-12210,Channahon,89,...,308.766332,7.645551,98.603232,308.766332,7.645365,98.524065,308.766332,7.645213,1.019634e+06,5618.560109
21975,21976,21199,5290.953710,1.146185e+06,197,12476,12209,197-i12476-12209,Channahon,4,...,16.006389,17.964852,7.104533,16.006389,18.186007,7.101355,16.006389,18.411775,1.896688e+05,2152.126622
21976,21977,21200,8658.035084,3.006150e+06,197,49607,12209,197-i49607-12209,Minooka,66,...,188.481960,2.980888,69.324813,188.481960,2.980836,69.302491,188.481960,2.980793,4.974787e+05,3523.409132

In [12]:
census.columns = census.columns.str.strip()


census = census.dropna(subset=["community_area"])

census["community_area"] = census["community_area"].astype(int)

census.to_csv("census_clean.csv", index=False)

census

,community_area,community_name,percent_housing_crowded,percent_poverty,percent_unemployed,percent_no_highschool,percent_age_dependency,PER CAPITA INCOME,hardship_index
0,1,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0
...,...,...,...,...,...,...,...,...,...
72,73,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48.0
73,74,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16.0
74,75,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30.0
75,76,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24.0
76,77,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19.0

In [37]:


forecast.columns = forecast.columns.str.strip()


forecast = forecast.rename(columns={"SUBZONE_09": "subzone"})


emp = forecast.melt(
    id_vars="subzone",
    value_vars=[c for c in forecast.columns if c.startswith("EMP_")],
    var_name="year",
    value_name="employment"
)

emp["year"] = emp["year"].str.replace("EMP_", "").astype(int)

forecast_clean = hh.merge(emp, on=["subzone", "year"])

forecast_clean = forecast_clean.sort_values(["subzone", "year"])

forecast_clean.to_csv("socioeconomic_forecast_clean.csv", index=False)

print(forecast_clean)

        subzone  year  households  employment
26760         1  2015  592.000000   47.455812
26761         1  2015  592.000000  743.879384
26762         1  2015    0.000000   47.455812
26763         1  2015    0.000000  743.879384
60871         1  2020  630.733558   50.358254
...         ...   ...         ...         ...
236585    16443  2045   48.609287   25.224106
253075    16443  2050   67.447535   53.182833
253076    16443  2050   67.447535   51.056128
270695    16443  2050   98.717559   53.182833
270696    16443  2050   98.717559   51.056128

[272888 rows x 4 columns]

In [44]:



print(population)

    Geography Type  Year Geography Population - Total Population - Age 0-17  \
0         Citywide  2018   Chicago          2,705,988               548,999
1         ZIP Code  2018     60601             14,675                   820
2         ZIP Code  2018     60602              1,244                   149
3         ZIP Code  2018     60603              1,174                    56
4         ZIP Code  2018     60604                782                    38
..             ...   ...       ...                ...                   ...
230       ZIP Code  2021     60626             50,295                 8,007
231       ZIP Code  2021     60628             64,489                13,734
232       ZIP Code  2021     60629            107,487                29,283
233       ZIP Code  2021     60630             55,591                11,093
234       ZIP Code  2021     60631             30,589                 6,925

    Population - Age 18-29 Population - Age 30-39 Population - Age 40-49  \
0                  552,935                456,321                336,457
1                    4,606                  2,792                  2,190
2                      435                    462                    135
3                      561                    101                     97
4                      303                    104                     51
..                     ...                    ...                    ...
230                 11,937                  8,965                  6,995
231                 11,638                  7,491                  7,593
232                 20,690                 13,227                 14,954
233                  7,053                  8,926                  7,337
234                  3,308                  4,357                  3,813

    Population - Age 50-59 Population - Age 60-69  ... Population - Age 18+  \
0                  312,965                262,991  ...            2,156,989
1                    1,333                  1,340  ...               13,855
2                       53                     10  ...                1,095
3                      197                     97  ...                1,118
4                      101                    130  ...                  744
..                     ...                    ...  ...                  ...
230                  6,738                  4,360  ...               42,288
231                  9,066                  6,930  ...               50,755
232                 11,096                  8,187  ...               78,204
233                  7,479                  7,975  ...               44,498
234                  4,657                  3,686  ...               23,664

    Population - Age 65+ Population - Female Population - Male  \
0                349,712           1,386,113         1,319,875
1                  2,075               7,484             7,191
2                      5                 551               693
3                    112                 601               573
4                     93                 413               369
..                   ...                 ...               ...
230                5,098              25,318            24,977
231               10,940              34,961            29,528
232               13,746              53,753            53,734
233                9,658              27,787            27,804
234                5,546              15,516            15,073

    Population - Latinx Population - Asian Non-Latinx  \
0               776,661                       179,841
1                 1,274                           NaN
2                    81                           NaN
3                   115                           NaN
4                    34                           NaN
..                  ...                           ...
230               9,694                         2,724
231               2,775                            79
232              79,111                           595
233              14,180                         7,122
234               4,491                         1,262

    Population - Black Non-Latinx Population - White Non-Latinx  \
0                         784,266                       899,980
1                             NaN                         9,677
2                             NaN                           788
3                             NaN                           707
4                             NaN                           479
..                            ...                           ...
230                        12,646                        23,029
231                        59,168                         1,462
232                        18,878                         7,650
233                         1,007                        31,325
234                           307                        23,360

    Population - Other Race Non-Latinx              Record ID
0                              119,467  Citywide-Chicago-2018
1                                  NaN    ZIP_Code-60601-2018
2                                  NaN    ZIP_Code-60602-2018
3                                  NaN    ZIP_Code-60603-2018
4                                  NaN    ZIP_Code-60604-2018
..                                 ...                    ...
230                              2,202    ZIP_CODE-60626-2021
231                              1,005    ZIP_CODE-60628-2021
232                              1,253    ZIP_CODE-60629-2021
233                              1,957    ZIP_CODE-60630-2021
234                              1,169    ZIP_CODE-60631-2021

[235 rows x 26 columns]